version: "3.3"

volumes:
    grafana_data: {}
    influxdb_data: {}

services:
  influxdb:
    image: "influxdb:2.2.0"
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - ./config/influxdb:/etc/influxdb2
      - influxdb_data:/var/lib/influxdb2
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUX_CONFIGS_PATH="/dev/null"
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=myOrg 
      - DOCKER_INFLUXDB_INIT_BUCKET=starlinkstats
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=myToken

  dish_grpc_influx_bulk_history:
    image: "ghcr.io/sparky8512/starlink-grpc-tools"
    restart: always
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=myToken
      - INFLUXDB_Bucket=starlinkstats
      - INFLUXDB_ORG=myOrg
    command: dish_grpc_influx2.py -v -t 5 bulk_history
    depends_on:
      - influxdb

  dish_grpc_influx:
    image: "ghcr.io/sparky8512/starlink-grpc-tools"
    restart: always
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=myToken
      - INFLUXDB_Bucket=starlinkstats
      - INFLUXDB_ORG=myOrg
    command: dish_grpc_influx2.py -v -t 10 status alert_detail
    depends_on:
      - influxdb

  grafana:
    image: "grafana/grafana-oss:8.4.6"
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
